name: Publish Docker

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@dev
      -name: Publish to registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        registry: docker.pkg.github.com
        name: docker.pkg.github.com/AndreiYa/nestjs-mongo-ecommerce-be/hue-ec.parf-be
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: 'develop'
